export const VINTED_CATEGORIES = [
  "Herren > Jeans > Gerade geschnittene Jeans",
  "Herren > Jeans > Slim Jeans",
  "Herren > Jeans > Bootcut Jeans",
  "Herren > Jeans > Skinny Jeans",
  "Herren > Hosen > Chinos",
  "Herren > Hosen > Jogginghosen",
  "Herren > Hosen > Outdoor- & Wanderhosen",
  "Herren > Hosen > Anzughosen",
  "Herren > Hosen > Stoffhosen",
  "Herren > Hosen > Shorts",
  "Herren > Jacken & Mäntel > Übergangsjacken",
  "Herren > Jacken & Mäntel > Daunenjacken",
  "Herren > Jacken & Mäntel > Westen",
  "Herren > Jacken & Mäntel > Lederjacken",
  "Herren > Jacken & Mäntel > Regenjacken",
  "Herren > Jacken & Mäntel > Mäntel",
  "Herren > Pullover & Sweatshirts > Pullover",
  "Herren > Pullover & Sweatshirts > Hoodies",
  "Herren > Pullover & Sweatshirts > Sweatshirts",
  "Herren > Pullover & Sweatshirts > Westen",
  "Herren > Pullover & Sweatshirts > Strickjacken",
  "Herren > T-Shirts & Tanktops > T-Shirts",
  "Herren > T-Shirts & Tanktops > Polos",
  "Herren > T-Shirts & Tanktops > Tanktops",
  "Herren > Hemden > Langarmhemden",
  "Herren > Hemden > Kurzarmhemden",
  "Herren > Schuhe > Sneaker",
  "Herren > Schuhe > Boots",
  "Herren > Schuhe > Halbschuhe",
  "Herren > Schuhe > Sandalen",
  "Herren > Accessoires > Mützen",
  "Herren > Accessoires > Gürtel",
  "Herren > Accessoires > Schals",
];
